# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Stream contract for all nvflare CLI command handlers
=====================================================

Current default (human-first):
    stdout — human-readable output (tables, summaries, prompts).
    stderr — errors and diagnostics.

JSON output mode (--format json):
    stdout — exactly one JSON envelope per command invocation:
        {"schema_version": "1", "status": "ok"|"error", "data": {...}}
    stderr — all human-readable output: progress, warnings, prompts, diagnostics.

Exceptions (plain text, outside the JSON contract):
    --help / -h         argparse usage text; agents use --schema instead
    --version           top-level utility path, not command output
    argparse errors     unrecognised-argument messages generated by argparse
"""

import json
import logging
import sys
from typing import Any, Optional

from nvflare.tool.cli_contract import SCHEMA_VERSION

logger = logging.getLogger(__name__)

# Module-level CLI state. This process is single-command/single-process, so a pair of globals is
# sufficient here, but they are intentionally process-global and not thread-safe.
# Possible values: "txt" (default, human-readable) or "json".
_output_format: str = "txt"
_connect_timeout: float = 5.0

_VALID_OUTPUT_STATUS = {"ok", "error"}


def set_output_format(fmt: str) -> None:
    """Set the output format for all cli_output functions.

    Called once by cli.py after --format is parsed.

    Args:
        fmt: "txt" (default) for human-readable output to stdout/stderr;
             "json" for a single machine-readable JSON envelope on stdout.
             "human" is accepted as a backward-compatible alias for "txt".
    """
    pass


def set_connect_timeout(value: float) -> None:
    """Set CLI connection timeout (seconds)."""
    pass


def get_connect_timeout() -> float:
    pass


def _is_json_mode() -> bool:
    pass


def is_json_mode() -> bool:
    """Public helper for checking JSON mode without exposing internals."""
    pass


def _human_stream():
    pass


def _render_table(data: Any) -> None:
    pass


def output(data: Any, fmt: Optional[str]) -> None:
    """Legacy output helper used by older cert/package command paths."""
    pass


def output_ok(data: Any, exit_code: int = 0) -> None:
    """Print command success output."""
    pass


def output_error(
    error_code: str,
    exit_code: int = 1,
    hint: str = None,
    data: Any = None,
    detail: str = None,
    **kwargs,
) -> None:
    """Print an error from ERROR_REGISTRY and exit. Never returns."""
    pass


def output_error_message(
    error_code: str,
    message: str,
    hint: str = None,
    fmt: Optional[str] = None,
    exit_code: int = 1,
    detail: str = None,
) -> None:
    """Print an explicit error message/hint pair and exit. Never returns."""
    pass


def output_usage_error(
    parser,
    detail: str,
    exit_code: int = 4,
    error_code: str = "INVALID_ARGS",
    message: str = "Invalid arguments.",
    hint: str = "Run with -h for usage.",
) -> None:
    """Print usage/help followed by a structured usage error and exit."""
    pass


def print_human(*args, **kwargs):
    """Print any human-readable text (progress, warnings, tables, diagnostics).

    Drop-in replacement for print() in CLI command handlers.
    Keeps stdout clean for the JSON envelope in JSON output mode.
    Usage: print_human("Starting shutdown of NVFLARE")
    """
    pass


def prompt_yn(question: str, default_no: bool = True) -> bool:
    """Write a Y/N prompt to stderr (json mode) or stdout (human mode) and read the answer from stdin.

    Returns True if the user answered Y/y, False otherwise.
    Writes the prompt to stderr in json mode so that stdout contains only JSON.
    Callers must check sys.stdin.isatty() and handle --force before calling.

    Usage:
        if not cmd_args.force:
            if not sys.stdin.isatty():
                output_error("INVALID_ARGS", exit_code=4, detail="use --force in non-interactive mode")
                return
            if not prompt_yn(f"Delete job '{job_id}'?"):
                print_human("Cancelled.")
                return
    """
    pass
