# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import os
import shutil
import traceback
from typing import List, Optional

from .constants import CtxKey, ProvisionMode, WorkDir
from .ctx import ProvisionContext
from .entity import Project
from .spec import Builder, Packager


class Provisioner:
    def __init__(self, root_dir: str, builders: List[Builder], packager: Optional[Packager] = None):
        """Workflow class that drive the provision process.

        Provisioner's tasks:

            - Maintain the provision workspace folder structure;
            - Invoke Builders to generate the content of each startup kit

        ROOT_WORKSPACE Folder Structure::

            root_workspace_dir_name: this is the root of the workspace
                project_dir_name: the root dir of the project, could be named after the project
                    resources: stores resource files (templates, configs, etc.) of the Provisioner and Builders
                    prod: stores the current set of startup kits (production)
                        participate_dir: stores content files generated by builders
                    wip: stores the set of startup kits to be created (WIP)
                        participate_dir: stores content files generated by builders
                    state: stores the persistent state of the Builders

        Args:
            root_dir (str): the directory path to hold all generated or intermediate folders
            builders (List[Builder]): all builders that will be called to build the content
        """
        self.root_dir = root_dir
        self.builders = builders
        self.packager = packager
        self.template = {}

        if not builders:
            raise ValueError("no builders are provided")

        for b in builders:
            if not isinstance(b, Builder):
                raise ValueError(f"builders must all be Builder type but got {type(b)}")

        if packager:
            if not isinstance(packager, Packager):
                raise ValueError(f"packager must be Packager type but got {type(packager)}")

    def add_template(self, template: dict):
        pass

    @staticmethod
    def _check_method(logger, method_name: str):
        pass

    def provision(self, project: Project, mode=None, logger=None) -> ProvisionContext:
        """Provision a specified project.

        Args:
            project: the project to be provisioned.
            mode: provision mode: either "poc" or "normal". If not specified, default to "normal".
            logger: a logger object to be used for message logging. If not specified, default to print.
                The logger must implement 4 methods: debug, info, warning, error.
                The logger object does NOT have to be based on logging.Logger. It could be used for
                collecting information into memory and displayed to end user at the end of provision.

        Returns: a ProvisionContext that contains properties created during provision, especially a
            property (CtxKey.CURRENT_PROD_DIR) that specifies where the provision result is stored.

        """
        pass

    def _build(self, project: Project, mode=None, logger=None) -> ProvisionContext:

        pass
