# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime
import ipaddress
import json
import os
import secrets
import shutil
import string
from base64 import b64decode, b64encode
from pathlib import Path

import yaml
from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.x509.oid import NameOID

from nvflare.lighter.tool_consts import NVFLARE_SIG_FILE, NVFLARE_SUBMITTER_CRT_FILE


class Identity:
    def __init__(self, name: str, org: str = None, role: str = None):
        self.name = name
        self.org = org
        self.role = role


def _host_to_subject_alt_name(host: str):
    pass


def generate_cert(
    subject: Identity,
    issuer: Identity,
    signing_pri_key,
    subject_pub_key,
    valid_days=360,
    ca=False,
    server_default_host=None,
    server_additional_hosts=None,
):
    pass


def serialize_pri_key(pri_key, passphrase=None):
    pass


def serialize_cert(cert):
    pass


def generate_keys():
    pass


def x509_name(cn_name, org_name=None, role=None):
    pass


def load_crt(path):
    pass


def load_crt_bytes(data: bytes):
    pass


def cert_to_dict(cert):
    pass


def generate_password(passlen=16):
    pass


def sign_content(content, signing_pri_key, return_str=True):
    pass


def _content_padding():
    pass


def _content_hash_algo():
    pass


def verify_content(content, signature, public_key):
    pass


def verify_cert(cert_to_be_verified, root_ca_public_key):
    pass


def load_private_key(data: str):
    pass


def load_private_key_file(file_path):
    pass


def sign_folders(folder, signing_pri_key, crt_path=None, max_depth=9999, signature_file=NVFLARE_SIG_FILE):
    pass


def verify_folder_signature(src_folder, root_ca_path, single_signer=False, signature_file=NVFLARE_SIG_FILE):
    """Verify the signature of each file in one folder recursively.

    This function iterates over all files in one folder verifying its signature stored in the signature_file
    of that folder.  The signature is generated either by the NVFLARE_SUBMITTER_CRT_FILE or root_ca_path.

    When single_signer is True, signature is generated by root_ca_path, which exists in one place.
    When single_signer is False, every folder contains NVFLARE_SUBMITTER_CRT_FILE, whose subject generates the signatures.
    In this case, the certificate chain is also built and verified from NVFLARE_SUBMITTER_CRT_FILE to root CA.

    Args:
        src_folder (str): The folder to be verified.
        root_ca_path (str): the path to root CA file.
        single_signer (bool): True means all signatures are from root CA.  False means from NVFLARE_SUBMITTER_CRT_FILE of each folder.
          Defaults to False.
        signature_file (str): The file name to store signature.  Defaults to NVFLARE_SIG_FILE.

    Returns:
        True if all files have valid signatures.
        False if any file fails signature check.

    """
    pass


def sign_all(content_folder, signing_pri_key):
    pass


def load_yaml(file):

    pass


def _resolve_include_path(root, item):
    pass


def load_yaml_include(root, yaml_data):
    pass


def sh_replace(src, mapping_dict):
    pass


def update_project_server_name_config(project_config: dict, old_server_name, server_name) -> dict:
    pass


def update_participant_server_name(project_config, old_server_name, new_server_name):
    pass


def update_server_default_host(project_config, default_host):
    """Update the default_host property of the Server in the project config.
    If a client does not explicitly specify "connect_to", it will use the default_host to connect to server.
    This is mainly used for POC, where the default_host is set to localhost.

    Args:
        project_config: the project config dict
        default_host: value of the default host

    Returns: the updated project_config

    """
    pass


def update_project_server_name(project_file: str, old_server_name, server_name):
    pass


def update_storage_locations(
    local_dir: str,
    workspace: str,
    default_resource_name: str = "resources.json.default",
    job_storage_name: str = "jobs-storage",
    snapshot_storage_name: str = "snapshot-storage",
):
    """Creates resources.json with snapshot-storage and jobs-storage set as folders directly under the workspace
    for the provided local_dir."""
    pass


def make_dirs(dirs):
    pass


def _write(file_full_path, content, mode, exe=False):
    pass


def write(file_full_path, content, mode, exe=False):
    pass


def add_component_to_resources(resources_file: str, component: dict):
    """Add a component to the resources file, merging with existing components.

    Args:
        resources_file: The name of the resource file
        component: The component to add
    """
    pass
