# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import io
import json
import os
import re
import subprocess
import tempfile

from nvflare.dashboard.config import PropertyManager
from nvflare.lighter.constants import PropKey
from nvflare.lighter.entity import Project as ProvProject
from nvflare.lighter.impl.aws import AWSBuilder
from nvflare.lighter.impl.azure import AzureBuilder
from nvflare.lighter.impl.cert import CertBuilder
from nvflare.lighter.impl.signature import SignatureBuilder
from nvflare.lighter.impl.static_file import StaticFileBuilder
from nvflare.lighter.impl.workspace import WorkspaceBuilder
from nvflare.lighter.provisioner import Provisioner

from .cert import deserialize_ca_key
from .models import Client, Project, User
from .store import Store, inc_dl


class DummyLogger:
    """This dummy logger is used to suppress all log messages generated by the Provisioner, except for errors.
    We print error messages to stdout.
    """

    def info(self, msg: str):
        pass

    def error(self, msg: str):
        pass

    def debug(self, msg: str):
        pass

    def warning(self, msg: str):
        pass


def _get_provisioner(prop_mgr: PropertyManager, root_dir: str, scheme, docker_image=None):
    pass


def gen_server_blob(key):
    pass


def _gen_kit(download_key, prepare_target_cb=None, **cb_kwargs):
    # validate download_key
    pass


def gen_client_blob(key, id):
    pass


def _prepare_client(prop_mgr: PropertyManager, prov_project: ProvProject, client_id):
    pass


def gen_user_blob(key, id):
    pass


def _prepare_user(prop_mgr: PropertyManager, prov_project: ProvProject, user_id):
    pass
